/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import RegraDeNegocios.Estoque;
import javax.swing.JOptionPane;

/**
 *
 * @author 1
 */
public class ExcProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExcProd
     */
    public ExcProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cil = new javax.swing.JButton();
        sprite = new javax.swing.JButton();
        kibe = new javax.swing.JButton();
        jButtonDoce = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jac = new javax.swing.JButton();
        pcocada = new javax.swing.JButton();
        forma = new javax.swing.JButton();
        carte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        paodqj = new javax.swing.JButton();
        pastel = new javax.swing.JButton();
        emp = new javax.swing.JButton();
        cox = new javax.swing.JButton();
        coca = new javax.swing.JButton();
        fanta = new javax.swing.JButton();
        sucoL = new javax.swing.JButton();
        SucoG = new javax.swing.JButton();
        bei = new javax.swing.JButton();
        tar = new javax.swing.JButton();
        bri = new javax.swing.JButton();
        sonhogoiaba = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Excluir produto"));

        cil.setText("Pao cilindro");
        cil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilActionPerformed(evt);
            }
        });

        sprite.setText("Sprite");
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });

        kibe.setText("Kibe");
        kibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kibeActionPerformed(evt);
            }
        });

        jButtonDoce.setText("Cocada");
        jButtonDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoceActionPerformed(evt);
            }
        });

        jLabel1.setText("Qual produto deseja excluir ?");

        jac.setText("Pao jaco");
        jac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacActionPerformed(evt);
            }
        });

        pcocada.setText("Pao cocada");
        pcocada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcocadaActionPerformed(evt);
            }
        });

        forma.setText("Pao de forma");
        forma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaActionPerformed(evt);
            }
        });

        carte.setText("Pao carteira");
        carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteActionPerformed(evt);
            }
        });

        jLabel2.setText("Pães");

        paodqj.setText("Pao de queijo");
        paodqj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paodqjActionPerformed(evt);
            }
        });

        pastel.setText("Pastel de queijo");
        pastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastelActionPerformed(evt);
            }
        });

        emp.setText("Empada de frango");
        emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empActionPerformed(evt);
            }
        });

        cox.setText("Coxinha de frango");
        cox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coxActionPerformed(evt);
            }
        });

        coca.setText("Coca cola");
        coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaActionPerformed(evt);
            }
        });

        fanta.setText("Fanta laranja");
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });

        sucoL.setText("Suco de laranja");
        sucoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucoLActionPerformed(evt);
            }
        });

        SucoG.setText("Suco de goiaba");
        SucoG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucoGActionPerformed(evt);
            }
        });

        bei.setText("Beijinho");
        bei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beiActionPerformed(evt);
            }
        });

        tar.setText("Tartilete");
        tar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarActionPerformed(evt);
            }
        });

        bri.setText("Brigadeiro");
        bri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                briActionPerformed(evt);
            }
        });

        sonhogoiaba.setText("Sonho de goiaba");
        sonhogoiaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonhogoiabaActionPerformed(evt);
            }
        });

        jLabel3.setText("Doces");

        jLabel4.setText("Bebidas");

        jLabel5.setText("Salgados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(177, 177, 177))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(96, 96, 96)
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sonhogoiaba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDoce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sucoL, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(SucoG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kibe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paodqj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forma, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(carte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pcocada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDoce)
                    .addComponent(sprite)
                    .addComponent(kibe)
                    .addComponent(jac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fanta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sucoL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcocada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carte))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(paodqj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pastel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sonhogoiaba)
                            .addComponent(SucoG)
                            .addComponent(cox)
                            .addComponent(forma))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão cilindro"));
    }//GEN-LAST:event_cilActionPerformed

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Sprite"));
    }//GEN-LAST:event_spriteActionPerformed

    private void kibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kibeActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Kibe"));
    }//GEN-LAST:event_kibeActionPerformed

    private void jButtonDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoceActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Cocada"));
    }//GEN-LAST:event_jButtonDoceActionPerformed

    private void jacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão jaco"));
    }//GEN-LAST:event_jacActionPerformed

    private void pcocadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcocadaActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão cocada"));
    }//GEN-LAST:event_pcocadaActionPerformed

    private void formaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão de forma"));
    }//GEN-LAST:event_formaActionPerformed

    private void carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão carteira"));
    }//GEN-LAST:event_carteActionPerformed

    private void paodqjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paodqjActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pão de queijo"));
    }//GEN-LAST:event_paodqjActionPerformed

    private void pastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastelActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Pastel de queijo"));
    }//GEN-LAST:event_pastelActionPerformed

    private void empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Empada de frango"));
    }//GEN-LAST:event_empActionPerformed

    private void coxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coxActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Coxinha de frango"));
    }//GEN-LAST:event_coxActionPerformed

    private void cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Coca cola"));
    }//GEN-LAST:event_cocaActionPerformed

    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Fanta laranja"));
    }//GEN-LAST:event_fantaActionPerformed

    private void sucoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucoLActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Suco de laranja"));
    }//GEN-LAST:event_sucoLActionPerformed

    private void SucoGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucoGActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Suco de goiaba"));
    }//GEN-LAST:event_SucoGActionPerformed

    private void beiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beiActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Beijinho"));
    }//GEN-LAST:event_beiActionPerformed

    private void tarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Tartilete"));
    }//GEN-LAST:event_tarActionPerformed

    private void briActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_briActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Brigadeiro"));
    }//GEN-LAST:event_briActionPerformed

    private void sonhogoiabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonhogoiabaActionPerformed
        Estoque e = new Estoque();
        JOptionPane.showMessageDialog(null, e.excProd("Sonho de goiaba"));
    }//GEN-LAST:event_sonhogoiabaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SucoG;
    private javax.swing.JButton bei;
    private javax.swing.JButton bri;
    private javax.swing.JButton carte;
    private javax.swing.JButton cil;
    private javax.swing.JButton coca;
    private javax.swing.JButton cox;
    private javax.swing.JButton emp;
    private javax.swing.JButton fanta;
    private javax.swing.JButton forma;
    private javax.swing.JButton jButtonDoce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jac;
    private javax.swing.JButton kibe;
    private javax.swing.JButton paodqj;
    private javax.swing.JButton pastel;
    private javax.swing.JButton pcocada;
    private javax.swing.JButton sonhogoiaba;
    private javax.swing.JButton sprite;
    private javax.swing.JButton sucoL;
    private javax.swing.JButton tar;
    // End of variables declaration//GEN-END:variables
}
